// Copyright 2026 H4D-CDE Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Airspace & Conflict Detection Domain Types.
 * Implements data structures aligned with Sahadevan et al. (ICSPIS 2025)
 * and ASTM F3548-21 Standard Specification for UAS Traffic Management (UTM).
 */

export interface GeoPoint {
  lat: number;
  lon: number;
  altMeters?: number;
  altFt?: number;
  timestamp?: number;
}

export interface VoxelKey {
  h3Index: string;
  altBinFt: number;
  timeBinS: number;
  resolution: number;
}

export interface AircraftState {
  id: string;
  callsign: string;
  lat: number;
  lon: number;
  altFt: number;
  groundSpeedKt: number;
  headingDeg: number;
  verticalSpeedFpm: number;
  originIcao: string;
  destIcao: string;
  currentVoxel: VoxelKey;
  progressPercent: number;
  status: "NOMINAL" | "WARNING" | "CRITICAL_CONFLICT" | "REROUTED";
  trajectory: GeoPoint[];
}

export interface ConflictRecord {
  id: string;
  flightIdA: string;
  flightIdB: string;
  conflictType: "SAME_VOXEL" | "NEIGHBOR_VOXEL";
  h3Cell: string;
  altBinFt: number;
  timeBinS: number;
  distanceMeters: number;
  closureRateMps: number;
  headingDiffDeg: number;
  riskScore: number;
  severity: "LOW" | "MEDIUM" | "CRITICAL";
  detectedAtUnixMs: number;
  timeToCPASeconds: number;
  // 7-D Feature vector values
  features: {
    nEntities: number;
    closureRateMps: number;
    headingDiffDeg: number;
    localTrafficDensity: number;
    sectorLoadForecast: number;
    windShearKt: number;
    visibilityKm: number;
  };
  // Advisory resolution generated by voxel engine
  advisory?: AdvisoryResolution;
}

export interface AdvisoryResolution {
  targetEntityId: string;
  resolutionType: "DELAY" | "ALTITUDE_CHANGE" | "REROUTE";
  recommendedDeltaTSeconds?: number;
  recommendedNewAltFt?: number;
  newWaypointH3?: string[];
  costScore: number;
  rationale: string;
  estimatedSeparationMeters: number;
}

export interface FlightPlanSubmission {
  entityId: string;
  originIcao: string;
  destinationIcao: string;
  eobtUnixMs: number;
  cruiseAltitudeFt: number;
  cruiseSpeedKt: number;
  waypoints: GeoPoint[];
}

export interface ASTMValidationResult {
  valid: boolean;
  standard: "ASTM F3548-21" | "ICAO Doc 4444";
  horizontalSeparationNm: number;
  verticalSeparationFt: number;
  rejectionReason?: string;
  authorizedAt?: string;
}

export interface AuditBlock {
  blockIndex: number;
  timestamp: string;
  voxelKey: string;
  entityId: string;
  eventType: string;
  prevHash: string;
  blockHash: string;
  isValid: boolean;
  tampered?: boolean;
}

export interface SystemServiceStatus {
  name: string;
  endpoint: string;
  status: "ONLINE" | "DEGRADED" | "OFFLINE";
  latencyMs: number;
  type: "GRPC" | "REST" | "INFRA";
}

export interface BenchmarkMetricsData {
  timeN2793NaiveS: number;
  timeN2793H4DS: number;
  timeN27930NaiveS: number;
  timeN27930H4DS: number;
  speedupPercent: number;
  opsReductionFactor: number;
  totalConflicts: number;
  sameVoxelConflicts: number;
  neighborVoxelConflicts: number;
  trajectoryMaeM: number;
  riskAucRoc: number;
  demandMapePercent: number;
}
